plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/leap-day@v0.2.0
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_links:
  enabled: true
include:
  - Proposal.md